### PR TITLE
Replace Pre/PostCommitTransactor with OnCommitTransactor

### PR DESCRIPTION
**Pull request by miyconst**
- **Issue**: [Unify Pre & Post commit transactor decorators #20](https://github.com/Starcounter/Starcounter.Database.Extensions/issues/20).

### CODE REVIEW

**Review by bigwad — APPROVED** [review]

**Comment by miyconst** [comment]
@bigwad are you just tired of my pull requests or you really don't have anything to add? It rarely happens when you accept a pull request without a single comment. 😄

**Comment by bigwad** [comment]
Hurry up with merging until I don't change my mind 😉 
Seriously, looks good. Optimization of `GetUserDefinedType` is likely to be required, but it's no different from the old implementation as I guess you know it.
 Also, two limitations of the old implementation are still in place:
- how to pass a user-defined context into a pre-commit hook
- hot to configure two hooks. 
But I didn't expect them to be covered in this PR.

**Comment by per-samuelsson** [comment]
> * hot to configure two hooks.
>   But I didn't expect them to be covered in this PR.

I don't think it's a top-prio either. It can be addressed in an application, minus that it won't suffice if some library would need to hook into committing, but I think those cases would be marginal.

**Comment by miyconst** [comment]
>Optimization of `GetUserDefinedType` is likely to be required..

This, I think, is kinda important, because most of the callbacks will rely on this feature. Should I take this on me and try to use `SetSpec` for the type identification.

**Comment by miyconst** [comment]
[Add an easy way to identify user defined type from IDatabaseContext.IChangeTracker #1095](https://github.com/Starcounter/Starcounter.Nova/issues/1095).

**Pull request merged**
