### PR TITLE
Initial extensions

### PR DESCRIPTION
**Pull request by per-samuelsson**
Supersedes https://github.com/Starcounter/Docs/pull/284. 
And provide our current take on https://github.com/Starcounter/Starcounter.Nova/issues/1051.

Not decided yet if we'll make a package over it, or just share it like we planned with these utilities in `Docs`. I can see pros and cons of both, but none is really important at this point.

### CODE REVIEW

**Comment by per-samuelsson** [comment]
cc @miyconst @bigwad

**Review by miyconst — APPROVED** [review]
Looks good. Approving.

**Comment by bigwad** [comment]
I like the code. The only thing I'm worried about is distribution. I hope we don't get into nuget versioning hell again. Also, I guess we have to decide on it soon in order to pass 3.0 rc to customers

**Review by bigwad — APPROVED** [review]

**Comment by miyconst** [comment]
>I hope we don't get into nuget versioning hell again.

I would pick one of the following alternatives:

- We keep close source & in the main repository, distributed together with all other packages.
- We don't distribute it as a package at all, only providing sources.

**Comment by bigwad** [comment]
>We keep close source & in the main repository, distributed together with all other packages.

We can build keep the same versioning scheme for both repos and deliver all packages at once. The fact that they're in two repos makes administration harder, but still manageable.

>We don't distribute it as a package at all, only providing sources.

From a customer PoV, I'd hate it.

**Comment by per-samuelsson** [comment]
> > We don't distribute it as a package at all, only providing sources.
> 
> From a customer PoV, I'd hate it.

Me too, to be honest. But at the same time, that was the idea when similar things were under `Docs` and even before that, when we asked customers to start from scratch themselves, just given them an idea about it via samples.

> We can build keep the same versioning scheme for both repos and deliver all packages at once. The fact that they're in two repos makes administration harder, but still manageable.

I think this is what I'm leaning towards as well, for the moment being. But let's give it another round of thinking, together, before we decide. We can still merge this as a start (and then the code is there for anyone to start looking at, or use) and then we complement with some distribution schema as a next step.

**Pull request merged**
